server:
  port: 7000
spring:
  application:
    name: teacher-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli-school?characterEncoding=utf-8&useSSL=false&timezone=asia/shanghai
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
